### ISSUE TITLE
Get logical result on cloth_v0 / cloth_corner

### ISSUE THREAD

**Issue by csingh27sewts** [csingh27sewts/Masterarbeit#7]
When running the main file with cloth_sewts_exp1, the results are random. Test the trusted cloth_v0 / cloth_corner for use with the SAC pipeline

**Comment by csingh27** [comment]
Possible reasons for agent not learning : 
* Implementation is wrong
* Need to run for more no. of epochs

**Comment by csingh27** [comment]
Redundant issue
