### ISSUE TITLE
Memory gets full error for stable baselines implementation

### ISSUE THREAD

**Issue by csingh27** [csingh27sewts/Masterarbeit#77]

**Comment by csingh27** [comment]
Downgrade numpy to 1.15 as this problem arises in later versions of numpy

**Comment by csingh27sewts** [comment]
Reduce replay buffer size 
buffer_size in model SAC arguments

**Comment by csingh27sewts** [comment]
Problem is due to the environment as memory does not accumulate for cart pole problem

**Comment by csingh27sewts** [comment]
Was due to matplotlib plt.imshow() which was accumulating the memory
